### ISSUE TITLE
ERR_INVALID_CALLBACK when logfile is deleted

### ISSUE THREAD

**Issue by rafipiccolo** [jandre/always-tail#18]
Hello,
i have an exception with the code from readme when logfile get deleted.

#> node --version
v10.15.1
#> node tail.js
got line: aaa
got line: abc
fs.js:137
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.close (fs.js:395:20)
    at next (/root/scripts/logpusher/node_modules/always-tail/index.js:27:12)
    at /root/scripts/logpusher/node_modules/always-tail/index.js:52:31
    at FSReqWrap.oncomplete (fs.js:155:5)

**Comment by vrybdpkt** [comment]
There is a pull that covers that

https://github.com/jandre/always-tail/pull/16/files
